apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-cache
  namespace: kserve-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: standard
